### ISSUE TITLE
Klasa is better than commando

### ISSUE THREAD

**Issue by MrJacz** [alexdominat/jailbreakbot#6]

**Comment by cfanoulis** [comment]
I second this

**Comment by kyranet** [comment]
I third this

**Comment by Tylertron1998** [comment]
I fourth this

**Comment by AdityaTD** [comment]
I fifth this

**Comment by Emy** [comment]
I sixth this

**Comment by QuantumlyTangled** [comment]
I seventh this

**Comment by 1Conan** [comment]
I eight this

**Comment by cfanoulis** [comment]
Maybe we should rewrite it ourselves

Also hello people's emails

**Comment by olvrb** [comment]
[dd-botkit](https://www.npmjs.com/package/dd-botkit) is better

**Comment by cfanoulis** [comment]
`git delete yourself`

**Comment by kyranet** [comment]
> [dd-botkit](https://www.npmjs.com/package/dd-botkit) is better

I find that hard to believe, it modifies discord.js' interface, plus [questionable code](https://github.com/dynastic/BotKit/blob/770949f8db700adf7911070f53a640283cd1dd7a/src/commands/api.ts#L74).

**Comment by Favna** [comment]
> dd-botkit is better

The fact that they list "an internet connection" as a prerequisite for the package says enough about the quality of you ask me.

**Comment by 1Conan** [comment]
Issue fixed Emy/janet
